{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce142aa9-890a-4204-ac0d-83a78bb3bdeb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "import random\n",
    "\n",
    "class HangmanGame:\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.root.title(\"Hangman Game\")\n",
    "        self.create_widgets()\n",
    "        self.word_list = [\n",
    "            \"PYTHON\", \"TKINTER\", \"HANGMAN\", \"DEVELOPER\", \"PROGRAMMING\", \"ALGORITHM\", \n",
    "            \"DATABASE\", \"APPLICATION\", \"MACHINE\", \"LEARNING\", \"ARTIFICIAL\", \"INTELLIGENCE\",\n",
    "            \"COMPUTER\", \"SCIENCE\", \"TECHNOLOGY\", \"INNOVATION\", \"ENGINEERING\", \"SOFTWARE\",\n",
    "            \"HARDWARE\", \"DEBUGGING\", \"SCRIPT\", \"CODE\", \"DEBUG\", \"FUNCTION\", \"VARIABLE\", \n",
    "            \"OBJECT\", \"CLASS\", \"MODULE\", \"PACKET\", \"NETWORK\", \"SECURITY\", \"ENCRYPTION\", \n",
    "            \"DECRYPTION\", \"SERVER\", \"CLIENT\", \"USER\", \"INTERFACE\", \"ALGORITHM\", \"RECURSION\",\n",
    "            \"SYNCHRONIZATION\", \"MULTITHREADING\", \"CONCURRENCY\", \"PARALLEL\", \"COMPUTATION\",\n",
    "            \"DEBUGGER\", \"EXCEPTION\", \"FRAMEWORK\", \"LIBRARY\", \"API\", \"JSON\", \"XML\", \n",
    "            \"WEB\", \"SERVER\", \"CLIENT\", \"REQUEST\", \"RESPONSE\", \"ENDPOINT\", \"ROUTING\", \n",
    "            \"URL\", \"SESSION\", \"COOKIE\", \"AUTHENTICATION\", \"AUTHORIZATION\", \"TOKEN\", \"LOGIN\",\n",
    "            \"LOGOUT\", \"PERMISSION\", \"DATABASE\", \"SQL\", \"NOSQL\", \"QUERY\", \"INDEX\", \n",
    "            \"TRANSACTION\", \"BACKUP\", \"RESTORE\", \"REPLICATION\", \"SHARDING\", \"OPTIMIZATION\",\n",
    "            \"SCALABILITY\", \"ARCHITECTURE\", \"DESIGN\", \"PATTERN\", \"BEST\", \"PRACTICES\"\n",
    "        ]\n",
    "        self.reset_game()\n",
    "\n",
    "    def create_widgets(self):\n",
    "        # Headline\n",
    "        self.headline = tk.Label(self.root, text=\"All the words are computer science related\", \n",
    "                                 font=(\"Courier\", 16, \"bold\"), fg=\"white\", bg=\"black\")\n",
    "        self.headline.pack(fill=tk.X, pady=10)\n",
    "\n",
    "        # Word Display\n",
    "        self.word_display = tk.Label(self.root, text=\"\", font=(\"Courier\", 28, \"bold\"), fg=\"blue\")\n",
    "        self.word_display.pack(pady=20)\n",
    "\n",
    "        # Hangman Canvas\n",
    "        self.hangman_canvas = tk.Canvas(self.root, width=200, height=200, bg=\"white\")\n",
    "        self.hangman_canvas.pack(pady=20)\n",
    "\n",
    "        # Guessed Letters Display\n",
    "        self.guessed_letters_display = tk.Label(self.root, text=\"Guessed Letters:\", font=(\"Courier\", 18), fg=\"red\")\n",
    "        self.guessed_letters_display.pack(pady=10)\n",
    "\n",
    "        # Hint Display\n",
    "        self.hint_display = tk.Label(self.root, text=\"Hint: (3 remaining)\", font=(\"Courier\", 14), fg=\"green\")\n",
    "        self.hint_display.pack(pady=10)\n",
    "\n",
    "        # Entry and Buttons\n",
    "        self.entry = tk.Entry(self.root, font=(\"Arial\", 18))\n",
    "        self.entry.pack(pady=10)\n",
    "        self.submit_button = tk.Button(self.root, text=\"Submit Guess\", command=self.submit_guess)\n",
    "        self.submit_button.pack(pady=10)\n",
    "\n",
    "        self.hint_button = tk.Button(self.root, text=\"Get Hint\", command=self.give_hint)\n",
    "        self.hint_button.pack(pady=10)\n",
    "\n",
    "        self.restart_button = tk.Button(self.root, text=\"Restart Game\", command=self.reset_game)\n",
    "        self.restart_button.pack(pady=10)\n",
    "        self.exit_button = tk.Button(self.root, text=\"Exit\", command=self.root.quit)\n",
    "        self.exit_button.pack(pady=10)\n",
    "\n",
    "    def reset_game(self):\n",
    "        self.word = random.choice(self.word_list)\n",
    "        self.guessed_letters = set()\n",
    "        self.attempts = 0\n",
    "        self.max_attempts = 6\n",
    "        self.hints_remaining = 3\n",
    "        self.update_word_display()\n",
    "        self.hint_display.config(text=f\"Hint: ({self.hints_remaining} remaining)\")\n",
    "        self.draw_hangman(self.attempts)\n",
    "\n",
    "    def update_word_display(self):\n",
    "        display_word = ' '.join([letter if letter in self.guessed_letters else '_' for letter in self.word])\n",
    "        self.word_display.config(text=display_word)\n",
    "\n",
    "    def submit_guess(self):\n",
    "        guess = self.entry.get().upper()\n",
    "        if guess and len(guess) == 1 and guess.isalpha():\n",
    "            if guess in self.guessed_letters:\n",
    "                messagebox.showinfo(\"Info\", \"You already guessed that letter.\")\n",
    "            elif guess in self.word:\n",
    "                self.guessed_letters.add(guess)\n",
    "                self.update_word_display()\n",
    "                if set(self.word) == self.guessed_letters:\n",
    "                    messagebox.showinfo(\"Congratulations\", \"You won!\")\n",
    "                    self.reset_game()\n",
    "            else:\n",
    "                self.attempts += 1\n",
    "                self.draw_hangman(self.attempts)\n",
    "                if self.attempts >= self.max_attempts:\n",
    "                    messagebox.showinfo(\"Game Over\", f\"You lost! The word was {self.word}.\")\n",
    "                    self.reset_game()\n",
    "        else:\n",
    "            messagebox.showwarning(\"Invalid Input\", \"Please enter a single letter.\")\n",
    "\n",
    "    def give_hint(self):\n",
    "        if self.hints_remaining > 0:\n",
    "            unguessed_letters = [letter for letter in self.word if letter not in self.guessed_letters]\n",
    "            if unguessed_letters:\n",
    "                hint_letter = random.choice(unguessed_letters)\n",
    "                self.hint_display.config(text=f\"Hint: {hint_letter} ({self.hints_remaining - 1} remaining)\")\n",
    "                self.hints_remaining -= 1\n",
    "            else:\n",
    "                self.hint_display.config(text=\"No more hints available!\")\n",
    "        else:\n",
    "            self.hint_display.config(text=\"No more hints available!\")\n",
    "\n",
    "    def draw_hangman(self, stage):\n",
    "        self.hangman_canvas.delete(\"all\")\n",
    "        if stage >= 1:\n",
    "            self.hangman_canvas.create_line(100, 150, 100, 50, width=2)\n",
    "            self.hangman_canvas.create_line(50, 50, 150, 50, width=2)\n",
    "        if stage >= 2:\n",
    "            self.hangman_canvas.create_line(150, 50, 150, 80, width=2)\n",
    "        if stage >= 3:\n",
    "            self.hangman_canvas.create_oval(130, 80, 170, 120, width=2)\n",
    "        if stage >= 4:\n",
    "            self.hangman_canvas.create_line(150, 120, 150, 150, width=2)\n",
    "        if stage >= 5:\n",
    "            self.hangman_canvas.create_line(130, 150, 170, 150, width=2)\n",
    "        if stage >= 6:\n",
    "            self.hangman_canvas.create_line(130, 80, 150, 60, width=2)\n",
    "            self.hangman_canvas.create_line(150, 60, 170, 80, width=2)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    app = HangmanGame(root)\n",
    "    root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ef00024d-43bc-428c-99bb-6fc824955fc6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
